services:
    # nginx + react
    frontend:
        image: ghcr.io/jpfrazz/blitz-auction-frontend:latest
        build: ./frontend/
        container_name: auction-frontend
        restart: always
        ports:
            - "80:80"
        depends_on:
            - backend
        networks:
            - auction_net

    # rust axum
    backend:
        image: ghcr.io/jpfrazz/blitz-auction-backend:latest
        build: ./backend/
        container_name: auction-backend
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            - DB_CONN_STRING=$DB_CONN_STRING
            - OAUTH_CLIENT_ID=$OAUTH_CLIENT_ID
            - OAUTH_CLIENT_SECRET=$OAUTH_CLIENT_SECRET
            - AXUM_SERVER_ADDR=0.0.0.0:3000
        networks:
            - auction_net

    # postgres db
    db:
        image: postgres:18-trixie
        container_name: auction-db
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
        volumes:
            - db_data:/var/lib/postgresql
        networks:
            - auction_net

networks:
    auction_net:
        driver: bridge

volumes:
    db_data:
