services:
    # nginx + react
    frontend:
        image: ghcr.io/jpfrazz/blitz-auction-frontend:latest
        build:
            context: ./frontend/
            dockerfile: ../dockerfiles/frontend-nginx.Dockerfile
        container_name: auction-frontend
        restart: always
        env_file:
            - .env
        depends_on:
            - backend
        networks:
            - auction_net

    # rust axum
    backend:
        image: ghcr.io/jpfrazz/blitz-auction-backend:latest
        build:
            context: ./backend/
            dockerfile: ../dockerfiles/backend.Dockerfile
        container_name: auction-backend
        restart: always
        volumes:
            - ./backend/migrations:/app/migrations
        environment:
            - DB_CONN_STRING=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - auction_net

    # postgres db
    db:
        image: postgres:18-trixie
        container_name: auction-db
        restart: always
        env_file:
            - .env
        volumes:
            - db_data:/var/lib/postgresql
            - ./db_init:/docker-entrypoint-initdb.d
        networks:
            - auction_net

networks:
    auction_net:
        driver: bridge

volumes:
    db_data:
